// Generated by https://quicktype.io

export interface IUser {
    jwt:  string;
    user: User;
}

export interface User {
    id:        number;
    username:  string;
    email:     string;
    provider:  string;
    confirmed: boolean;
    blocked:   boolean;
    createdAt: string;
    updatedAt: string;
}

export interface LoginData {
    identifier: string;
    password: string;
  }
